### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by AdrianSkierniewski** [geo-io/geojson#1]
Hi,

First of all, I'd like to thank you for creating all those packages, they're very helpful for me.
I'm refactoring some library using geo-io packages and I was thinking about using this package as well, but there is no stable version. Are you planning to create a release for this repo or it isn't ready for prod?

**Comment by jsor** [comment]
[Here](https://github.com/geo-io/geojson/releases/tag/v1.0.0) it is. I know the docs are nearly non-existent, so feel free to open issues in the repos if you have any questions :)

**Comment by AdrianSkierniewski** [comment]
Thank you very much :)
